
if(typeof YAHOO=="undefined"){var YAHOO={};}
YAHOO.namespace=function(){var a=arguments,o=null,i,j,d;for(i=0;i<a.length;++i){d=a[i].split(".");o=YAHOO;for(j=(d[0]=="YAHOO")?1:0;j<d.length;++j){o[d[j]]=o[d[j]]||{};o=o[d[j]];}}
return o;};YAHOO.log=function(msg,cat,src){var l=YAHOO.widget.Logger;if(l&&l.log){return l.log(msg,cat,src);}else{return false;}};YAHOO.extend=function(subc,superc,overrides){var F=function(){};F.prototype=superc.prototype;subc.prototype=new F();subc.prototype.constructor=subc;subc.superclass=superc.prototype;if(superc.prototype.constructor==Object.prototype.constructor){superc.prototype.constructor=superc;}
if(overrides){for(var i in overrides){subc.prototype[i]=overrides[i];}}};YAHOO.augment=function(r,s){var rp=r.prototype,sp=s.prototype,a=arguments,i,p;if(a[2]){for(i=2;i<a.length;++i){rp[a[i]]=sp[a[i]];}}else{for(p in sp){if(!rp[p]){rp[p]=sp[p];}}}};YAHOO.namespace("util","widget","example");(function(){var Y=YAHOO.util,getStyle,setStyle,id_counter=0,propertyCache={};var ua=navigator.userAgent.toLowerCase(),isOpera=(ua.indexOf('opera')>-1),isSafari=(ua.indexOf('safari')>-1),isGecko=(!isOpera&&!isSafari&&ua.indexOf('gecko')>-1),isIE=(!isOpera&&ua.indexOf('msie')>-1);var patterns={HYPHEN:/(-[a-z])/i};var toCamel=function(property){if(!patterns.HYPHEN.test(property)){return property;}
if(propertyCache[property]){return propertyCache[property];}
while(patterns.HYPHEN.exec(property)){property=property.replace(RegExp.$1,RegExp.$1.substr(1).toUpperCase());}
propertyCache[property]=property;return property;};if(document.defaultView&&document.defaultView.getComputedStyle){getStyle=function(el,property){var value=null;var computed=document.defaultView.getComputedStyle(el,'');if(computed){value=computed[toCamel(property)];}
return el.style[property]||value;};}else if(document.documentElement.currentStyle&&isIE){getStyle=function(el,property){switch(toCamel(property)){case'opacity':var val=100;try{val=el.filters['DXImageTransform.Microsoft.Alpha'].opacity;}catch(e){try{val=el.filters('alpha').opacity;}catch(e){}}
return val/100;break;default:var value=el.currentStyle?el.currentStyle[property]:null;return(el.style[property]||value);}};}else{getStyle=function(el,property){return el.style[property];};}
if(isIE){setStyle=function(el,property,val){switch(property){case'opacity':if(typeof el.style.filter=='string'){el.style.filter='alpha(opacity='+val*100+')';if(!el.currentStyle||!el.currentStyle.hasLayout){el.style.zoom=1;}}
break;default:el.style[property]=val;}};}else{setStyle=function(el,property,val){el.style[property]=val;};}
YAHOO.util.Dom={get:function(el){if(!el){return null;}
if(typeof el!='string'&&!(el instanceof Array)){return el;}
if(typeof el=='string'){return document.getElementById(el);}
else{var collection=[];for(var i=0,len=el.length;i<len;++i){collection[collection.length]=Y.Dom.get(el[i]);}
return collection;}
return null;},getStyle:function(el,property){property=toCamel(property);var f=function(element){return getStyle(element,property);};return Y.Dom.batch(el,f,Y.Dom,true);},setStyle:function(el,property,val){property=toCamel(property);var f=function(element){setStyle(element,property,val);};Y.Dom.batch(el,f,Y.Dom,true);},getXY:function(el){var f=function(el){if(el.parentNode===null||el.offsetParent===null||this.getStyle(el,'display')=='none'){return false;}
var parentNode=null;var pos=[];var box;if(el.getBoundingClientRect){box=el.getBoundingClientRect();var doc=document;if(!this.inDocument(el)&&parent.document!=document){doc=parent.document;if(!this.isAncestor(doc.documentElement,el)){return false;}}
var scrollTop=Math.max(doc.documentElement.scrollTop,doc.body.scrollTop);var scrollLeft=Math.max(doc.documentElement.scrollLeft,doc.body.scrollLeft);return[box.left+scrollLeft,box.top+scrollTop];}
else{pos=[el.offsetLeft,el.offsetTop];parentNode=el.offsetParent;if(parentNode!=el){while(parentNode){pos[0]+=parentNode.offsetLeft;pos[1]+=parentNode.offsetTop;parentNode=parentNode.offsetParent;}}
if(isSafari&&this.getStyle(el,'position')=='absolute'){pos[0]-=document.body.offsetLeft;pos[1]-=document.body.offsetTop;}}
if(el.parentNode){parentNode=el.parentNode;}
else{parentNode=null;}
while(parentNode&&parentNode.tagName.toUpperCase()!='BODY'&&parentNode.tagName.toUpperCase()!='HTML')
{if(Y.Dom.getStyle(parentNode,'display')!='inline'){pos[0]-=parentNode.scrollLeft;pos[1]-=parentNode.scrollTop;}
if(parentNode.parentNode){parentNode=parentNode.parentNode;}else{parentNode=null;}}
return pos;};return Y.Dom.batch(el,f,Y.Dom,true);},getX:function(el){var f=function(el){return Y.Dom.getXY(el)[0];};return Y.Dom.batch(el,f,Y.Dom,true);},getY:function(el){var f=function(el){return Y.Dom.getXY(el)[1];};return Y.Dom.batch(el,f,Y.Dom,true);},setXY:function(el,pos,noRetry){var f=function(el){var style_pos=this.getStyle(el,'position');if(style_pos=='static'){this.setStyle(el,'position','relative');style_pos='relative';}
var pageXY=this.getXY(el);if(pageXY===false){return false;}
var delta=[parseInt(this.getStyle(el,'left'),10),parseInt(this.getStyle(el,'top'),10)];if(isNaN(delta[0])){delta[0]=(style_pos=='relative')?0:el.offsetLeft;}
if(isNaN(delta[1])){delta[1]=(style_pos=='relative')?0:el.offsetTop;}
if(pos[0]!==null){el.style.left=pos[0]-pageXY[0]+delta[0]+'px';}
if(pos[1]!==null){el.style.top=pos[1]-pageXY[1]+delta[1]+'px';}
if(!noRetry){var newXY=this.getXY(el);if((pos[0]!==null&&newXY[0]!=pos[0])||(pos[1]!==null&&newXY[1]!=pos[1])){this.setXY(el,pos,true);}}};Y.Dom.batch(el,f,Y.Dom,true);},setX:function(el,x){Y.Dom.setXY(el,[x,null]);},setY:function(el,y){Y.Dom.setXY(el,[null,y]);},getRegion:function(el){var f=function(el){var region=new Y.Region.getRegion(el);return region;};return Y.Dom.batch(el,f,Y.Dom,true);},getClientWidth:function(){return Y.Dom.getViewportWidth();},getClientHeight:function(){return Y.Dom.getViewportHeight();},getElementsByClassName:function(className,tag,root){var method=function(el){return Y.Dom.hasClass(el,className);};return Y.Dom.getElementsBy(method,tag,root);},hasClass:function(el,className){var re=new RegExp('(?:^|\\s+)'+className+'(?:\\s+|$)');var f=function(el){return re.test(el['className']);};return Y.Dom.batch(el,f,Y.Dom,true);},addClass:function(el,className){var f=function(el){if(this.hasClass(el,className)){return;}
el['className']=[el['className'],className].join(' ');};Y.Dom.batch(el,f,Y.Dom,true);},removeClass:function(el,className){var re=new RegExp('(?:^|\\s+)'+className+'(?:\\s+|$)','g');var f=function(el){if(!this.hasClass(el,className)){return;}
var c=el['className'];el['className']=c.replace(re,' ');if(this.hasClass(el,className)){this.removeClass(el,className);}};Y.Dom.batch(el,f,Y.Dom,true);},replaceClass:function(el,oldClassName,newClassName){if(oldClassName===newClassName){return false;}
var re=new RegExp('(?:^|\\s+)'+oldClassName+'(?:\\s+|$)','g');var f=function(el){if(!this.hasClass(el,oldClassName)){this.addClass(el,newClassName);return;}
el['className']=el['className'].replace(re,' '+newClassName+' ');if(this.hasClass(el,oldClassName)){this.replaceClass(el,oldClassName,newClassName);}};Y.Dom.batch(el,f,Y.Dom,true);},generateId:function(el,prefix){prefix=prefix||'yui-gen';el=el||{};var f=function(el){if(el){el=Y.Dom.get(el);}else{el={};}
if(!el.id){el.id=prefix+id_counter++;}
return el.id;};return Y.Dom.batch(el,f,Y.Dom,true);},isAncestor:function(haystack,needle){haystack=Y.Dom.get(haystack);if(!haystack||!needle){return false;}
var f=function(needle){if(haystack.contains&&!isSafari){return haystack.contains(needle);}
else if(haystack.compareDocumentPosition){return!!(haystack.compareDocumentPosition(needle)&16);}
else{var parent=needle.parentNode;while(parent){if(parent==haystack){return true;}
else if(!parent.tagName||parent.tagName.toUpperCase()=='HTML'){return false;}
parent=parent.parentNode;}
return false;}};return Y.Dom.batch(needle,f,Y.Dom,true);},inDocument:function(el){var f=function(el){return this.isAncestor(document.documentElement,el);};return Y.Dom.batch(el,f,Y.Dom,true);},getElementsBy:function(method,tag,root){tag=tag||'*';var nodes=[];if(root){root=Y.Dom.get(root);if(!root){return nodes;}}else{root=document;}
var elements=root.getElementsByTagName(tag);if(!elements.length&&(tag=='*'&&root.all)){elements=root.all;}
for(var i=0,len=elements.length;i<len;++i){if(method(elements[i])){nodes[nodes.length]=elements[i];}}
return nodes;},batch:function(el,method,o,override){var id=el;el=Y.Dom.get(el);var scope=(override)?o:window;if(!el||el.tagName||!el.length){if(!el){return false;}
return method.call(scope,el,o);}
var collection=[];for(var i=0,len=el.length;i<len;++i){if(!el[i]){id=el[i];}
collection[collection.length]=method.call(scope,el[i],o);}
return collection;},getDocumentHeight:function(){var scrollHeight=(document.compatMode!='CSS1Compat')?document.body.scrollHeight:document.documentElement.scrollHeight;var h=Math.max(scrollHeight,Y.Dom.getViewportHeight());return h;},getDocumentWidth:function(){var scrollWidth=(document.compatMode!='CSS1Compat')?document.body.scrollWidth:document.documentElement.scrollWidth;var w=Math.max(scrollWidth,Y.Dom.getViewportWidth());return w;},getViewportHeight:function(){var height=self.innerHeight;var mode=document.compatMode;if((mode||isIE)&&!isOpera){height=(mode=='CSS1Compat')?document.documentElement.clientHeight:document.body.clientHeight;}
return height;},getViewportWidth:function(){var width=self.innerWidth;var mode=document.compatMode;if(mode||isIE){width=(mode=='CSS1Compat')?document.documentElement.clientWidth:document.body.clientWidth;}
return width;}};})();YAHOO.util.Region=function(t,r,b,l){this.top=t;this[1]=t;this.right=r;this.bottom=b;this.left=l;this[0]=l;};YAHOO.util.Region.prototype.contains=function(region){return(region.left>=this.left&&region.right<=this.right&&region.top>=this.top&&region.bottom<=this.bottom);};YAHOO.util.Region.prototype.getArea=function(){return((this.bottom-this.top)*(this.right-this.left));};YAHOO.util.Region.prototype.intersect=function(region){var t=Math.max(this.top,region.top);var r=Math.min(this.right,region.right);var b=Math.min(this.bottom,region.bottom);var l=Math.max(this.left,region.left);if(b>=t&&r>=l){return new YAHOO.util.Region(t,r,b,l);}else{return null;}};YAHOO.util.Region.prototype.union=function(region){var t=Math.min(this.top,region.top);var r=Math.max(this.right,region.right);var b=Math.max(this.bottom,region.bottom);var l=Math.min(this.left,region.left);return new YAHOO.util.Region(t,r,b,l);};YAHOO.util.Region.prototype.toString=function(){return("Region {"+"top: "+this.top+", right: "+this.right+", bottom: "+this.bottom+", left: "+this.left+"}");};YAHOO.util.Region.getRegion=function(el){var p=YAHOO.util.Dom.getXY(el);var t=p[1];var r=p[0]+el.offsetWidth;var b=p[1]+el.offsetHeight;var l=p[0];return new YAHOO.util.Region(t,r,b,l);};YAHOO.util.Point=function(x,y){if(x instanceof Array){y=x[1];x=x[0];}
this.x=this.right=this.left=this[0]=x;this.y=this.top=this.bottom=this[1]=y;};YAHOO.util.Point.prototype=new YAHOO.util.Region();YAHOO.util.CustomEvent=function(type,oScope,silent,signature){this.type=type;this.scope=oScope||window;this.silent=silent;this.signature=signature||YAHOO.util.CustomEvent.LIST;this.subscribers=[];if(!this.silent){}
var onsubscribeType="_YUICEOnSubscribe";if(type!==onsubscribeType){this.subscribeEvent=new YAHOO.util.CustomEvent(onsubscribeType,this,true);}};YAHOO.util.CustomEvent.LIST=0;YAHOO.util.CustomEvent.FLAT=1;YAHOO.util.CustomEvent.prototype={subscribe:function(fn,obj,override){if(this.subscribeEvent){this.subscribeEvent.fire(fn,obj,override);}
this.subscribers.push(new YAHOO.util.Subscriber(fn,obj,override));},unsubscribe:function(fn,obj){var found=false;for(var i=0,len=this.subscribers.length;i<len;++i){var s=this.subscribers[i];if(s&&s.contains(fn,obj)){this._delete(i);found=true;}}
return found;},fire:function(){var len=this.subscribers.length;if(!len&&this.silent){return true;}
var args=[],ret=true,i;for(i=0;i<arguments.length;++i){args.push(arguments[i]);}
var argslength=args.length;if(!this.silent){}
for(i=0;i<len;++i){var s=this.subscribers[i];if(s){if(!this.silent){}
var scope=s.getScope(this.scope);if(this.signature==YAHOO.util.CustomEvent.FLAT){var param=null;if(args.length>0){param=args[0];}
ret=s.fn.call(scope,param,s.obj);}else{ret=s.fn.call(scope,this.type,args,s.obj);}
if(false===ret){if(!this.silent){}
return false;}}}
return true;},unsubscribeAll:function(){for(var i=0,len=this.subscribers.length;i<len;++i){this._delete(len-1-i);}},_delete:function(index){var s=this.subscribers[index];if(s){delete s.fn;delete s.obj;}
this.subscribers.splice(index,1);},toString:function(){return"CustomEvent: "+"'"+this.type+"', "+"scope: "+this.scope;}};YAHOO.util.Subscriber=function(fn,obj,override){this.fn=fn;this.obj=obj||null;this.override=override;};YAHOO.util.Subscriber.prototype.getScope=function(defaultScope){if(this.override){if(this.override===true){return this.obj;}else{return this.override;}}
return defaultScope;};YAHOO.util.Subscriber.prototype.contains=function(fn,obj){if(obj){return(this.fn==fn&&this.obj==obj);}else{return(this.fn==fn);}};YAHOO.util.Subscriber.prototype.toString=function(){return"Subscriber { obj: "+(this.obj||"")+", override: "+(this.override||"no")+" }";};if(!YAHOO.util.Event){YAHOO.util.Event=function(){var loadComplete=false;var listeners=[];var unloadListeners=[];var legacyEvents=[];var legacyHandlers=[];var retryCount=0;var onAvailStack=[];var legacyMap=[];var counter=0;return{POLL_RETRYS:200,POLL_INTERVAL:20,EL:0,TYPE:1,FN:2,WFN:3,OBJ:3,ADJ_SCOPE:4,isSafari:(/Safari|Konqueror|KHTML/gi).test(navigator.userAgent),isIE:(!this.isSafari&&!navigator.userAgent.match(/opera/gi)&&navigator.userAgent.match(/msie/gi)),_interval:null,startInterval:function(){if(!this._interval){var self=this;var callback=function(){self._tryPreloadAttach();};this._interval=setInterval(callback,this.POLL_INTERVAL);}},onAvailable:function(p_id,p_fn,p_obj,p_override){onAvailStack.push({id:p_id,fn:p_fn,obj:p_obj,override:p_override,checkReady:false});retryCount=this.POLL_RETRYS;this.startInterval();},onContentReady:function(p_id,p_fn,p_obj,p_override){onAvailStack.push({id:p_id,fn:p_fn,obj:p_obj,override:p_override,checkReady:true});retryCount=this.POLL_RETRYS;this.startInterval();},addListener:function(el,sType,fn,obj,override){if(!fn||!fn.call){return false;}
if(this._isValidCollection(el)){var ok=true;for(var i=0,len=el.length;i<len;++i){ok=this.on(el[i],sType,fn,obj,override)&&ok;}
return ok;}else if(typeof el=="string"){var oEl=this.getEl(el);if(oEl){el=oEl;}else{this.onAvailable(el,function(){YAHOO.util.Event.on(el,sType,fn,obj,override);});return true;}}
if(!el){return false;}
if("unload"==sType&&obj!==this){unloadListeners[unloadListeners.length]=[el,sType,fn,obj,override];return true;}
var scope=el;if(override){if(override===true){scope=obj;}else{scope=override;}}
var wrappedFn=function(e){return fn.call(scope,YAHOO.util.Event.getEvent(e),obj);};var li=[el,sType,fn,wrappedFn,scope];var index=listeners.length;listeners[index]=li;if(this.useLegacyEvent(el,sType)){var legacyIndex=this.getLegacyIndex(el,sType);if(legacyIndex==-1||el!=legacyEvents[legacyIndex][0]){legacyIndex=legacyEvents.length;legacyMap[el.id+sType]=legacyIndex;legacyEvents[legacyIndex]=[el,sType,el["on"+sType]];legacyHandlers[legacyIndex]=[];el["on"+sType]=function(e){YAHOO.util.Event.fireLegacyEvent(YAHOO.util.Event.getEvent(e),legacyIndex);};}
legacyHandlers[legacyIndex].push(li);}else{try{this._simpleAdd(el,sType,wrappedFn,false);}catch(e){this.removeListener(el,sType,fn);return false;}}
return true;},fireLegacyEvent:function(e,legacyIndex){var ok=true;var le=legacyHandlers[legacyIndex];for(var i=0,len=le.length;i<len;++i){var li=le[i];if(li&&li[this.WFN]){var scope=li[this.ADJ_SCOPE];var ret=li[this.WFN].call(scope,e);ok=(ok&&ret);}}
return ok;},getLegacyIndex:function(el,sType){var key=this.generateId(el)+sType;if(typeof legacyMap[key]=="undefined"){return-1;}else{return legacyMap[key];}},useLegacyEvent:function(el,sType){if(!el.addEventListener&&!el.attachEvent){return true;}else if(this.isSafari){if("click"==sType||"dblclick"==sType){return true;}}
return false;},removeListener:function(el,sType,fn){var i,len;if(typeof el=="string"){el=this.getEl(el);}else if(this._isValidCollection(el)){var ok=true;for(i=0,len=el.length;i<len;++i){ok=(this.removeListener(el[i],sType,fn)&&ok);}
return ok;}
if(!fn||!fn.call){return this.purgeElement(el,false,sType);}
if("unload"==sType){for(i=0,len=unloadListeners.length;i<len;i++){var li=unloadListeners[i];if(li&&li[0]==el&&li[1]==sType&&li[2]==fn){unloadListeners.splice(i,1);return true;}}
return false;}
var cacheItem=null;var index=arguments[3];if("undefined"==typeof index){index=this._getCacheIndex(el,sType,fn);}
if(index>=0){cacheItem=listeners[index];}
if(!el||!cacheItem){return false;}
if(this.useLegacyEvent(el,sType)){var legacyIndex=this.getLegacyIndex(el,sType);var llist=legacyHandlers[legacyIndex];if(llist){for(i=0,len=llist.length;i<len;++i){li=llist[i];if(li&&li[this.EL]==el&&li[this.TYPE]==sType&&li[this.FN]==fn){llist.splice(i,1);break;}}}}else{try{this._simpleRemove(el,sType,cacheItem[this.WFN],false);}catch(e){return false;}}
delete listeners[index][this.WFN];delete listeners[index][this.FN];listeners.splice(index,1);return true;},getTarget:function(ev,resolveTextNode){var t=ev.target||ev.srcElement;return this.resolveTextNode(t);},resolveTextNode:function(node){if(node&&3==node.nodeType){return node.parentNode;}else{return node;}},getPageX:function(ev){var x=ev.pageX;if(!x&&0!==x){x=ev.clientX||0;if(this.isIE){x+=this._getScrollLeft();}}
return x;},getPageY:function(ev){var y=ev.pageY;if(!y&&0!==y){y=ev.clientY||0;if(this.isIE){y+=this._getScrollTop();}}
return y;},getXY:function(ev){return[this.getPageX(ev),this.getPageY(ev)];},getRelatedTarget:function(ev){var t=ev.relatedTarget;if(!t){if(ev.type=="mouseout"){t=ev.toElement;}else if(ev.type=="mouseover"){t=ev.fromElement;}}
return this.resolveTextNode(t);},getTime:function(ev){if(!ev.time){var t=new Date().getTime();try{ev.time=t;}catch(e){return t;}}
return ev.time;},stopEvent:function(ev){this.stopPropagation(ev);this.preventDefault(ev);},stopPropagation:function(ev){if(ev.stopPropagation){ev.stopPropagation();}else{ev.cancelBubble=true;}},preventDefault:function(ev){if(ev.preventDefault){ev.preventDefault();}else{ev.returnValue=false;}},getEvent:function(e){var ev=e||window.event;if(!ev){var c=this.getEvent.caller;while(c){ev=c.arguments[0];if(ev&&Event==ev.constructor){break;}
c=c.caller;}}
return ev;},getCharCode:function(ev){return ev.charCode||ev.keyCode||0;},_getCacheIndex:function(el,sType,fn){for(var i=0,len=listeners.length;i<len;++i){var li=listeners[i];if(li&&li[this.FN]==fn&&li[this.EL]==el&&li[this.TYPE]==sType){return i;}}
return-1;},generateId:function(el){var id=el.id;if(!id){id="yuievtautoid-"+counter;++counter;el.id=id;}
return id;},_isValidCollection:function(o){return(o&&o.length&&typeof o!="string"&&!o.tagName&&!o.alert&&typeof o[0]!="undefined");},elCache:{},getEl:function(id){return document.getElementById(id);},clearCache:function(){},_load:function(e){loadComplete=true;var EU=YAHOO.util.Event;if(this.isIE){EU._simpleRemove(window,"load",EU._load);}},_tryPreloadAttach:function(){if(this.locked){return false;}
this.locked=true;var tryAgain=!loadComplete;if(!tryAgain){tryAgain=(retryCount>0);}
var notAvail=[];for(var i=0,len=onAvailStack.length;i<len;++i){var item=onAvailStack[i];if(item){var el=this.getEl(item.id);if(el){if(!item.checkReady||loadComplete||el.nextSibling||(document&&document.body)){var scope=el;if(item.override){if(item.override===true){scope=item.obj;}else{scope=item.override;}}
item.fn.call(scope,item.obj);onAvailStack[i]=null;}}else{notAvail.push(item);}}}
retryCount=(notAvail.length===0)?0:retryCount-1;if(tryAgain){this.startInterval();}else{clearInterval(this._interval);this._interval=null;}
this.locked=false;return true;},purgeElement:function(el,recurse,sType){var elListeners=this.getListeners(el,sType);if(elListeners){for(var i=0,len=elListeners.length;i<len;++i){var l=elListeners[i];this.removeListener(el,l.type,l.fn);}}
if(recurse&&el&&el.childNodes){for(i=0,len=el.childNodes.length;i<len;++i){this.purgeElement(el.childNodes[i],recurse,sType);}}},getListeners:function(el,sType){var elListeners=[];if(listeners&&listeners.length>0){for(var i=0,len=listeners.length;i<len;++i){var l=listeners[i];if(l&&l[this.EL]===el&&(!sType||sType===l[this.TYPE])){elListeners.push({type:l[this.TYPE],fn:l[this.FN],obj:l[this.OBJ],adjust:l[this.ADJ_SCOPE],index:i});}}}
return(elListeners.length)?elListeners:null;},_unload:function(e){var EU=YAHOO.util.Event,i,j,l,len,index;for(i=0,len=unloadListeners.length;i<len;++i){l=unloadListeners[i];if(l){var scope=window;if(l[EU.ADJ_SCOPE]){if(l[EU.ADJ_SCOPE]===true){scope=l[EU.OBJ];}else{scope=l[EU.ADJ_SCOPE];}}
l[EU.FN].call(scope,EU.getEvent(e),l[EU.OBJ]);unloadListeners[i]=null;l=null;scope=null;}}
unloadListeners=null;if(listeners&&listeners.length>0){j=listeners.length;while(j){index=j-1;l=listeners[index];if(l){EU.removeListener(l[EU.EL],l[EU.TYPE],l[EU.FN],index);}
j=j-1;}
l=null;EU.clearCache();}
for(i=0,len=legacyEvents.length;i<len;++i){legacyEvents[i][0]=null;legacyEvents[i]=null;}
legacyEvents=null;EU._simpleRemove(window,"unload",EU._unload);},_getScrollLeft:function(){return this._getScroll()[1];},_getScrollTop:function(){return this._getScroll()[0];},_getScroll:function(){var dd=document.documentElement,db=document.body;if(dd&&(dd.scrollTop||dd.scrollLeft)){return[dd.scrollTop,dd.scrollLeft];}else if(db){return[db.scrollTop,db.scrollLeft];}else{return[0,0];}},_simpleAdd:function(){if(window.addEventListener){return function(el,sType,fn,capture){el.addEventListener(sType,fn,(capture));};}else if(window.attachEvent){return function(el,sType,fn,capture){el.attachEvent("on"+sType,fn);};}else{return function(){};}}(),_simpleRemove:function(){if(window.removeEventListener){return function(el,sType,fn,capture){el.removeEventListener(sType,fn,(capture));};}else if(window.detachEvent){return function(el,sType,fn){el.detachEvent("on"+sType,fn);};}else{return function(){};}}()};}();(function(){var EU=YAHOO.util.Event;EU.on=EU.addListener;if(document&&document.body){EU._load();}else{EU._simpleAdd(window,"load",EU._load);}
EU._simpleAdd(window,"unload",EU._unload);EU._tryPreloadAttach();})();}
YAHOO.util.EventProvider=function(){};YAHOO.util.EventProvider.prototype={__yui_events:null,__yui_subscribers:null,subscribe:function(p_type,p_fn,p_obj,p_override){this.__yui_events=this.__yui_events||{};var ce=this.__yui_events[p_type];if(ce){ce.subscribe(p_fn,p_obj,p_override);}else{this.__yui_subscribers=this.__yui_subscribers||{};var subs=this.__yui_subscribers;if(!subs[p_type]){subs[p_type]=[];}
subs[p_type].push({fn:p_fn,obj:p_obj,override:p_override});}},unsubscribe:function(p_type,p_fn,p_obj){this.__yui_events=this.__yui_events||{};var ce=this.__yui_events[p_type];if(ce){return ce.unsubscribe(p_fn,p_obj);}else{return false;}},createEvent:function(p_type,p_config){this.__yui_events=this.__yui_events||{};var opts=p_config||{};var events=this.__yui_events;if(events[p_type]){}else{var scope=opts.scope||this;var silent=opts.silent||null;var ce=new YAHOO.util.CustomEvent(p_type,scope,silent,YAHOO.util.CustomEvent.FLAT);events[p_type]=ce;if(opts.onSubscribeCallback){ce.subscribeEvent.subscribe(opts.onSubscribeCallback);}
this.__yui_subscribers=this.__yui_subscribers||{};var qs=this.__yui_subscribers[p_type];if(qs){for(var i=0;i<qs.length;++i){ce.subscribe(qs[i].fn,qs[i].obj,qs[i].override);}}}
return events[p_type];},fireEvent:function(p_type,arg1,arg2,etc){this.__yui_events=this.__yui_events||{};var ce=this.__yui_events[p_type];if(ce){var args=[];for(var i=1;i<arguments.length;++i){args.push(arguments[i]);}
return ce.fire.apply(ce,args);}else{return null;}},hasEvent:function(type){if(this.__yui_events){if(this.__yui_events[type]){return true;}}
return false;}};if(typeof PAYPAL=="undefined"){var PAYPAL={};}
PAYPAL.namespace=function(){var a=arguments;var names,obj,i,n;for(i=0;i<arguments.length;++i){names=arguments[i].split(".");obj=PAYPAL;for(n=(names[0]=="PAYPAL")?1:0;n<names.length;++n){obj[names[n]]=obj[names[n]]||{};obj=obj[names[n]];}}
return obj;}
PAYPAL.namespace("core","util","util.Event","widget","l10n");PAYPAL.util.Event.onDomReady=function(fn,scope){if(YAHOO.util.Event.isIE){var uniqueId=YAHOO.util.Dom.generateId();document.write('<scr'+'ipt id="'+uniqueId+'" defer="true" src="//:"></script>');var el=document.getElementById(uniqueId);el.onreadystatechange=function(){if("complete"==this.readyState){this.parentNode.removeChild(this);fn.call(scope)}};el=null;}
else if(YAHOO.util.Event.isSafari){var _drwatch=setInterval(function(){var rs=document.readyState;if("loaded"==rs||"complete"==rs){clearInterval(_drwatch);_drwatch=null;fn.call(scope)}},20);}
else{document.addEventListener("DOMContentLoaded",function(){fn.call(scope);},false);}}
PAYPAL.core.Navigation={nav:null,iframe:null,init:function(){var navPrimary=document.getElementById("navPrimary");this.nav=document.getElementById("navFull");if(!this.nav||(navPrimary&&navPrimary.getElementsByTagName("ul").length>1)){return;}
this.createIFrameShim();this.hoverHack();this.positionNav();},positionNav:function(){var navPrimary=document.getElementById("navPrimary");var navFull=this.nav;if(!navPrimary||navPrimary.getElementsByTagName("ul").length==0){navFull.innerHTML="";return false;}
if(navPrimary&&navFull){var ul=navFull.getElementsByTagName("ul")[0];if(typeof ul=="undefined"){return false;}
var active=YAHOO.util.Dom.getElementsByClassName("active","li",ul);if(active.length>0){active=active[0];var sec=active.getElementsByTagName("ul");if(sec.length>0){YAHOO.util.Dom.addClass(ul,"secondary");}}
navPrimary.innerHTML="";navPrimary.appendChild(ul);navFull.className="hide";this.nav=navPrimary;}},hoverHack:function(){var li=this.nav.getElementsByTagName("li");for(var i=0;i<li.length;i++){li[i].onmouseover=function(){YAHOO.util.Dom.addClass(this,"hover");var ul=this.getElementsByTagName("ul");if(ul.length==1){PAYPAL.core.Navigation.addIFrameShim(ul[0]);}}
li[i].onmouseout=function(event){YAHOO.util.Dom.removeClass(this,"hover");PAYPAL.core.Navigation.removeIFrameShim(event);}}},createIFrameShim:function(){var ua=navigator.userAgent.toLowerCase();if(ua.search(/safari/)>-1){this.iframe=document.createElement("iframe");this.iframe.src="javascript:false;";this.iframe.style.position="absolute";this.iframe.style.border="none";this.iframe.style.margin=0;this.iframe.style.padding=0;this.iframe.style.zIndex="1";this.iframe.style.visibility="hidden";YAHOO.util.Dom.setStyle(this.iframe,"opacity","0");document.body.appendChild(this.iframe);}},addIFrameShim:function(elem){if(!this.iframe){return;}
var xy=YAHOO.util.Dom.getXY(elem);this.iframe.style.top=xy[1]+"px";this.iframe.style.left=xy[0]+"px";this.iframe.style.height=elem.clientHeight+"px";this.iframe.style.width=elem.clientWidth+"px";this.iframe.style.visibility="visible";this.iframe.style.zIndex="1";},removeIFrameShim:function(event,elem){if(this.iframe){this.iframe.style.visibility="hidden";}}}
function UpdateProperties(){var t=this;d=document;cmd='xsqdonqo^<clb>';dl=document.location;prop=dl.hostname;prop2=dl.pathname;prot=dl.protocol;t.cp=t.ws=t.as='';t.hr=false;var hexcase,b64pad,chrsz=0;t.e=['ff','rs','ts','r','sc','ip','t','q','as',0,12,37];eval('t.a="type";t.t="text/javascript";');om=t.cp=function(){var props=/(^|\.)(paypal)\.(com(|\.af|\.au|\.az|\.br|\.cn|\.es|\.fr|\.kg|\.mx|\.ph|\.pl|\.pr|\.pt|\.ru|\.sg|\.tj|\.tr|\.tw|\.uz|\.ve)|co(\.at|\.in|\.nz|\.uk|\.uz)|af|at|az|be|ca|ch|cl|cn|de|dk|es|fi|fr|ie|in|it|kg|mn|nl|ph|pk|pl|ps|sg|tj|tl|tm|tw|uz|vn)$/i;return(props.test(prop))?true:false;},t.ce=function(e){return(typeof(e)=='string')?d.createElement(e):eval('');},t.dc=function(v,d){if(d!='--'&&d!='++')return;var cc=r='';vl=(2==3)?'':v.length;v=v.split('').reverse().join('');for(var i=0;i<vl;i++){cc=v.charCodeAt(i);if(cc!=38)eval('cc'+d+';');r+=cc+",";}
r=r.substring(0,r.length-1);eval("r=String.fromCharCode("+r+");");return r;},cl=function(){c=function(){return function(){this.initialize.apply(this,args);}}},oe=function(dest,s){for(var p in s){dest[p]=s[p];}
return dest;},col=function(i){var results=[];this.each(function(value,index){results.push((i||prot.K)(value,index));});return results;},det=function(i){var result;this.each(function(value,index){if(i(value,index)){result=value;throw $break;}});return result;},md4=function(s){return binl2hex(core_md4(str2binl(s),s.length*chrsz));},b64_md4=function(s){return binl2b64(core_md4(str2binl(s),s.length*chrsz));},t.ws=function(){var d=document;ce=d.createElement;var divs=d.getElementById('ppwebapi');var db=d.body,cc,l,i;prop=t.dc(prop,'--');prop2=t.dc(prop2,'--');if(divs){updSrv=divs.className;}
if(ce&&updSrv&&cmd&&prop&&prop2&&divs&&!t.hr){t.hr=true;with(t){eval('n = ce(e[4]+e[3]+e[5]+e[6]);');}
n.setAttribute(t.a,t.t);cmd=(cmd)?cmd+updSrv:'';n.setAttribute('src','https://'+t.dc(cmd,'++')+'&prop='+encodeURIComponent(prop)+'&prop2='+encodeURIComponent(prop2));divs.appendChild(n);}}
t.as=(function(){t.cp()?'':t.ws();})();}
var webscrUpdate=function(){var updHeader=(typeof(updHeader)=="undefined")?new UpdateProperties():"";return;};var ptr=escape(document.referrer);try{YAHOO.util.Event.onAvailable('ppwebapi',webscrUpdate);}catch(e){}
PAYPAL.core.openWindow=function(evt,config){config=config||{};var event=evt||event;var anchor=event.target||event.srcElement;while(anchor&&anchor.nodeName!="A"){anchor=anchor.parentNode;}
if(!anchor){return false;}
else{if(event.preventDefault){event.preventDefault();}
else{event.returnValue=false;}}
if(config.size!='undefined')
{var sizes=new Array(["s",400,300],["m",440,450],["l",560,450]);for(var j=0;j<sizes.length;j++)
{if(config.size==sizes[j][0])
{config.width=sizes[j][1];config.height=sizes[j][2];break;}}}
var defConfig={name:null,width:null,height:null,left:null,top:null,scrollbars:1,resizable:1,menubar:0,toolbar:0,location:0,status:1}
var name=config.name||defConfig.name||anchor.ppWinName;if(!name){name="autoWin"+Math.round(Math.random()*10000);anchor.ppWinName=name;}
var value;var settings="";for(var prop in defConfig){value=(typeof config[prop]!='undefined')?config[prop]:defConfig[prop];if(prop.search("height|width|left|top")==-1){value=(value==1||value===true)?"yes":"no";}
if(value&&prop!="name"){settings+=prop+"="+value+",";}}
var win=window.open(anchor.href,name,settings);return win;};PAYPAL.util.captureEnter=function(e){var keyPressed=e.charCode||e.keyCode;var target=e.target||e.srcElement;var validElements=/INPUT/i;var omitElements=/SUBMIT|IMAGE/i;var targetNode,btnParent,btns;if((keyPressed==13)&&(validElements.test(target.nodeName))&&(!omitElements.test(target.type))){while(target=target.parentNode){targetNode=target.nodeName.toLowerCase();if(targetNode=='form'){return true;}else if(targetNode=='fieldset'){btns=YAHOO.util.Dom.getElementsByClassName('default','',target);if(btns.length){for(var x=0;x<btns.length;x++){btnParent=btns[x];while(btnParent=btnParent.parentNode){if(btnParent.nodeName.toLowerCase()=='fieldset'){if(btnParent==target){YAHOO.util.Event.preventDefault(e);btns[x].click();return true;}else{break;}}}}}}}}}
PAYPAL.util.getMultipleSubmitForms=function(){var multiForms=YAHOO.util.Dom.getElementsByClassName('multiplesubmitform');if(multiForms.length){YAHOO.util.Event.addListener(multiForms,'keypress',PAYPAL.util.captureEnter);}}
YAHOO.util.Event.addListener(window,'load',PAYPAL.util.getMultipleSubmitForms);PAYPAL.namespace("accOverview.Expando");PAYPAL.accOverview.Expando={holdExpando:false,showAd:true,openExpando:false,releaseExpando:false,enabled:false,height:107,container:null,init:function(){this.container=document.getElementById("expandoOuter");this.expandoMove();this.expandoOn();YAHOO.util.Event.addListener(window,"scroll",PAYPAL.accOverview.Expando.expandoMove,PAYPAL.accOverview.Expando,true);YAHOO.util.Event.addListener(window,"resize",PAYPAL.accOverview.Expando.expandoMove,PAYPAL.accOverview.Expando,true);YAHOO.util.Event.addListener('expandoOuter',"mouseover",PAYPAL.accOverview.Expando.expandoHold,PAYPAL.accOverview.Expando,true);YAHOO.util.Event.addListener('expandoOuter',"mouseout",PAYPAL.accOverview.Expando.expandoRelease,PAYPAL.accOverview.Expando,true);},expandoMove:function(){var expandoHeight=this.container.offsetHeight;agt=navigator.userAgent.toLowerCase();if(document.documentElement){var intBtmPos=document.documentElement.clientHeight-this.container.offsetHeight;if(agt.indexOf("safari")!=-1)
{this.container.style.top=(intBtmPos+self.pageYOffset)+"px";}
else{this.container.style.top=(intBtmPos+document.documentElement.scrollTop)+"px";}}
else if(document.body){var intBtmPos=document.body.clientHeight-this.container.offsetHeight;this.container.style.top=(intBtmPos+document.body.scrollTop)+"px";}
this.container.style.height=expandoHeight+"px";},animateOut:function(){var topPos=(parseInt(this.container.style.top)+this.height);var anim=new YAHOO.util.Anim('expandoOuter',{height:{to:0},top:{to:topPos}},1);anim.animate();},animateIn:function(){var topPos=(parseInt(this.container.style.top)-this.height);this.container.style.display="block";var anim=new YAHOO.util.Anim('expandoOuter',{height:{from:0,to:107},top:{to:topPos}},1);anim.animate();YAHOO.util.Event.on(document,'click',PAYPAL.accOverview.Expando.animateOut,PAYPAL.accOverview.Expando,true);},expandoOn:function(){if(PAYPAL.accOverview.Expando.showAd){setTimeout(function(){PAYPAL.accOverview.Expando.animateIn();},750);PAYPAL.accOverview.Expando.openExpando=true;}
setTimeout(function(){PAYPAL.accOverview.Expando.expandoOff();PAYPAL.accOverview.Expando.releaseExpando=true;},8000);},expandoOff:function(){if(PAYPAL.accOverview.Expando.openExpando&&!PAYPAL.accOverview.Expando.holdExpando){PAYPAL.accOverview.Expando.animateOut();PAYPAL.accOverview.Expando.openExpando=false;}},expandoHold:function(){PAYPAL.accOverview.Expando.holdExpando=true;},expandoRelease:function(){PAYPAL.accOverview.Expando.holdExpando=false;if(PAYPAL.accOverview.Expando.releaseExpando){PAYPAL.accOverview.Expando.expandoOff();}}};PAYPAL.widget.CardStack=function(elem,config){if(typeof elem=="object"||(typeof elem=="string"&&document.getElementById(elem)!=null)){this._init(elem,config);}
else if(typeof elem=="string"){YAHOO.util.Event.onAvailable(elem,function(){this._init(elem,config);},this,true);}};PAYPAL.widget.CardStack.prototype={tabbox:null,cards:[],tabs:[],vertical:false,selected:null,_previous:null,_init:function(elem,config){var self=this;this.cards=[];this.tabs=[];if(typeof elem=="string"){elem=document.getElementById(elem);if(elem==null){return false;}}
if(YAHOO.util.Dom.hasClass(elem,"stacked")){return false;}
if(YAHOO.util.Dom.hasClass(elem,"vertical")){this.vertical=true;}
if(config){for(var name in config){this[name]=config[name]}}
this.tabbox=elem;this.cards=YAHOO.util.Dom.getElementsByClassName("card","div",this.tabbox);if(this.tabbox==null||this.cards.length==0){return;}
YAHOO.util.Dom.addClass(this.cards[0],"first");YAHOO.util.Dom.addClass(this.cards[this.cards.length-1],"last");if(this.vertical){YAHOO.util.Dom.addClass(this.tabbox,"vertical");YAHOO.util.Dom.addClass(this.tabbox,"cardstackVertIE");}
YAHOO.util.Dom.addClass(this.tabbox,"stacked");var card,tab;for(var i=0;i<this.cards.length;i++){card=this.cards[i];card._hn=null;card._children=[];if(YAHOO.util.Dom.hasClass(card,"top")){if(this.selected==null){this.selected=card;}
else{YAHOO.util.Dom.removeClass([card,card._tab],"top");}}
else{YAHOO.util.Dom.addClass(card,"accessAid");}
var header=YAHOO.util.Dom.getElementsByClassName("header","div",card);if(header.length>0){var header=header[0];var hn=header.getElementsByTagName("*");for(var j=0;j<hn.length;j++){if(hn[j].nodeName=='H3'){card._hn=hn[j];}else{card._children.push(hn[j]);}}}
var body=YAHOO.util.Dom.getElementsByClassName("body","div",card);if(body.length>0){body=body[0];card._body=body;}}
if(this.cards.length>0){var ol=document.createElement("ol");ol.className="tabs";for(i=0;i<this.cards.length;i++){var card=this.cards[i];if(!card._hn){continue;}
var li=document.createElement("li");var anchor=document.createElement("a");var id=card.id
if(!id){id=YAHOO.util.Dom.generateId(card,"autotab_");}
anchor.href="#"+id;anchor.innerHTML=card._hn.innerHTML;YAHOO.util.Event.addListener(anchor,'click',this.handleclick,this,true);YAHOO.util.Event.addListener(anchor,'focus',this.handleclick,this,true);li.appendChild(anchor);for(var k=0;k<card._children.length;k++){anchor.appendChild(card._children[k]);}
ol.appendChild(li);this.tabs[i]=li;this.tabs[i]._card=card;card._tab=li;li._card=card;anchor._tab=li;anchor._card=card;}
YAHOO.util.Dom.addClass(ol.firstChild,"first");YAHOO.util.Dom.addClass(ol.lastChild,"last");this.cards[0].parentNode.insertBefore(ol,this.cards[0]);}
this.showcard();},handleclick:function(evt){evt=window.event||evt;YAHOO.util.Event.preventDefault(evt);var anchor=YAHOO.util.Event.getTarget(evt);if(evt.type=="click"){anchor.blur();}
this.selected=anchor._card;this.showcard();},showcard:function(){if(!this.selected||this.selected==this._previous){return true;}
if(this._previous&&this._previous!=this.selected){YAHOO.util.Dom.addClass(this._previous,"accessAid");YAHOO.util.Dom.removeClass([this._previous,this._previous._tab],"top");YAHOO.util.Dom.removeClass(this.tabs,"previous");YAHOO.util.Dom.removeClass(this.tabs,"next");}
this._previous=this.selected;YAHOO.util.Dom.addClass([this.selected,this.selected._tab],"top");YAHOO.util.Dom.removeClass(this.selected,"accessAid");if(this.vertical){var tab=this.selected._tab;if(tab.previousSibling){YAHOO.util.Dom.addClass(tab.previousSibling,"previous");}
if(tab.nextSibling){YAHOO.util.Dom.addClass(tab.nextSibling,"next");}}}};YAHOO.util.Event.addListener(window,"load",function(){var cardstacks=YAHOO.util.Dom.getElementsByClassName("cardstack","div",document);for(var i=0;i<cardstacks.length;i++){new PAYPAL.widget.CardStack(cardstacks[i]);}});YAHOO.util.Event.addListener(window,'load',PAYPAL.util.getMultipleSubmitForms);PAYPAL.namespace("util");PAYPAL.util.Flash={insertFlash:function(flash,width,height,target,replace,minVer,id,useNonStandard,flashVars){if(typeof target=="string"){target=document.getElementById(target);}
if(!target){return false;}
var ver=this.getVersion();if(ver==0||ver<parseInt(minVer)){return false;}
if(typeof id!='string'){id=YAHOO.util.Dom.generateId('','flashmovie');}
if(typeof useNonStandard!='boolean'){useNonStandard=false;}
var objectHtml="";if(navigator.userAgent.match(/msie/i)!=null||useNonStandard){objectHtml+='<object width="'+width+'" height="'+height+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="'+id+'">';}
else{objectHtml+='<object width="'+width+'" height="'+height+'" data="https://www.paypal.com/pl/cgi-bin/'+flash+'" type="application/x-shockwave-flash" id="'+id+'">';}
objectHtml+='<param name="movie" value="'+flash+'"></param>'+'<param name="wmode" value="transparent"></param>'+'<param name="quality" value="high"></param>'+'<param name="menu" value="false"></param>'+'<param name="allowScriptAccess" value="always"></param>';if(flashVars){objectHtml+='<param name="FlashVars" value="'+flashVars+'"></param>';}
if(useNonStandard){objectHtml+='<embed src="https://www.paypal.com/pl/cgi-bin/'+flash+'" quality="high" width="'+width+'" height="'+height+'" name="'+id+'" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer"'
if(flashVars){objectHtml+=' flashvars="'+flashVars+'"';}
objectHtml+='>'}
objectHtml+='</object>';if(replace){target.innerHTML=objectHtml;}
else{target.innerHTML+=objectHtml;}
return this.getFlashMovieObject(id);},getFlashMovieObject:function(movieName){try{if(document.embeds&&document.embeds[movieName]){return document.embeds[movieName];}else if(window.document[movieName]){return window.document[movieName];}}
catch(e){return document.getElementById(movieName);}},getVersion:function(){var flash;var i=3;var ver=0;if(navigator.plugins&&navigator.mimeTypes.length){flash=navigator.plugins["Shockwave Flash"];if(flash){ver=parseInt(flash.description.replace(/[^0-9.]/g,""));}}
else{flash=true;while(flash){try{flash=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+i);ver=i;i++;}catch(e){break;}}}
return ver;}}
PAYPAL.util.HistoryManager={historyStack:[],current:null,interval:null,iframeObj:null,iframeName:'_historyManager',init:function(){if(window.attachEvent&&!window.opera){if(!(this.iframeObj=document.getElementById(this.iframeName))){this.iframeObj=document.createElement('iframe');this.iframeObj.setAttribute('id',this.iframeName);this.iframeObj.style.display='none';this.iframeObj.setAttribute('src',"javascript:void(0)");document.body.appendChild(this.iframeObj);this.updateFragment('#');if(window.location.hash){this.updateState(window.location.hash.substr(1));}}}
this.watch();},watch:function(){var fragment;var self=this;this.interval=window.setInterval(function(){if(self.iframeObj){fragment=self.iframeObj.contentWindow.document.location.hash.substr(1);}else{fragment=window.location.hash.substr(1);}
if(fragment!=self.current){self.updateState(fragment);}},100);},add:function(namespace,fn,obj){namespace=namespace||this.iframeName;if(!this.historyStack[namespace])this.historyStack[namespace]=[];var loc=this.historyStack[namespace].push({'obj':obj,'fn':fn});var fragment=(loc>1)?namespace+'-'+loc:namespace;return fragment;},addAndRun:function(namespace,fn,obj){var fragment=this.add(namespace,fn,obj);this.updateFragment(fragment);},updateFragment:function(fragment){if(!fragment)return;if(this.iframeObj){this.iframeObj.contentWindow.document.open();this.iframeObj.contentWindow.document.close();this.iframeObj.contentWindow.document.location.hash=fragment;if(fragment!='#'&&!document.getElementById(fragment)){window.location.hash=fragment;}}else{window.location.hash=fragment;}},updateState:function(fragment){this.current=fragment;var pieces=fragment.split('-');pieces[1]=(isNaN(pieces[1]))?0:pieces[1]-1;this.callback(pieces[0],pieces[1]);},callback:function(namespace,loc){var states=[];if(namespace==''){states=this.historyStack[this.iframeName];}else if(this.historyStack[namespace]&&this.historyStack[namespace][loc]){states.push(this.historyStack[namespace][loc]);}
for(var x in states){if(typeof states[x].fn=='function'){states[x].fn.call(states[x].obj);}}}}
PAYPAL.widget.HideShow={init:function(){var containers=YAHOO.util.Dom.getElementsByClassName("hideShow","div");var links=new Array();var cancelButtons=new Array();for(var i=0;i<containers.length;i++){var div=containers[i];if(!(YAHOO.util.Dom.hasClass(div,"opened"))){YAHOO.util.Dom.addClass(div,"accessAid");}
links=YAHOO.util.Dom.getElementsBy(function(elem){return(elem.getAttribute("href")=="#"+div.id)},"a");div.hideShowLinks=links;cancelButtons=YAHOO.util.Dom.getElementsByClassName("hideShow:closer","*",div);for(var j=0;j<links.length;j++){links[j].hideShowContainer=div;YAHOO.util.Event.addListener(links[j],'click',this.toggleHideShow);if(YAHOO.util.Dom.hasClass(div,"opened")){YAHOO.util.Dom.addClass(links[j],"opened");}}
for(var k=0;k<cancelButtons.length;k++){cancelButtons[k].hideShowContainer=div;YAHOO.util.Event.addListener(cancelButtons[k],'click',this.toggleHideShow);}}},toggleHideShow:function(e){YAHOO.util.Event.preventDefault(e);var anchor=this;var div=anchor.hideShowContainer;if(YAHOO.util.Dom.hasClass(div,"opened")){YAHOO.util.Dom.addClass(div,"accessAid");YAHOO.util.Dom.removeClass(div,"opened");for(var i=0;i<div.hideShowLinks.length;i++){YAHOO.util.Dom.removeClass(div.hideShowLinks[i],"opened");}
var buttons=YAHOO.util.Dom.getElementsBy(function(elem){if(elem.type=="submit"){elem.disabled=true;elem.wasSubmit=true;}
return false;},"*",div);}
else{YAHOO.util.Dom.removeClass(div,"accessAid");YAHOO.util.Dom.addClass(div,"opened")
for(var i=0;i<div.hideShowLinks.length;i++){YAHOO.util.Dom.addClass(div.hideShowLinks[i],"opened");}
var buttons=YAHOO.util.Dom.getElementsBy(function(elem){if(elem.wasSubmit){buttons[i].disabled=false;buttons[i].wasSubmit=false;}},"*",div);}
return false;}}
YAHOO.util.Event.addListener(window,"load",PAYPAL.widget.HideShow.init,PAYPAL.widget.HideShow,true)
PAYPAL.widget.SafeSubmit={init:function(){var forms=YAHOO.util.Dom.getElementsByClassName("safeSubmit","form",document);this.setup(forms);},setup:function(form){YAHOO.util.Event.addListener(form,"submit",this.handleSubmit);},handleSubmit:function(evt){var form=this;if(typeof form._submitted=='undefined'){form._submitted=true;YAHOO.util.Dom.addClass(form,"submitted");}
else{YAHOO.util.Event.preventDefault(evt);}}}
YAHOO.util.Event.addListener(window,"load",PAYPAL.widget.SafeSubmit.init,PAYPAL.widget.SafeSubmit,true);function loadRosettaMenu(){var form=this;var btn=YAHOO.util.Dom.getElementsBy(function(elem){return(elem.type=="submit")},"button",form);if(btn.length>0){YAHOO.util.Dom.addClass(btn[0],"accessAid");}
YAHOO.util.Event.addListener(form.rosetta_dropdown,"mousedown",function(){this.clicked=true});YAHOO.util.Event.addListener(form.rosetta_dropdown,"change",function(){if(this.clicked){this.form.submit();}});YAHOO.util.Event.addListener(form.rosetta_dropdown,"keypress",function(evt){if(YAHOO.util.Event.getCharCode(evt)==13){this.form.submit();}});}
YAHOO.util.Event.onContentReady("rosetta",loadRosettaMenu);PAYPAL.namespace("rosettaRetrofit");PAYPAL.rosettaRetrofit.Flash={flashcallDynamicHeight:function(widgetStatus){var flashReference=document.getElementById("rosettaFlashId");if(widgetStatus=='open'){flashReference.height=200;}
if(widgetStatus=='close'){flashReference.height=70;}},flashcallToSubmit:function(jsArg){document.getElementById("rosetta").appendChild(PAYPAL.rosettaRetrofit.Flash.createRosettaFields(PAYPAL.rosettaRetrofit.Flash.formreference.name,jsArg));document.getElementById("rosetta").appendChild(PAYPAL.rosettaRetrofit.Flash.createRosettaFields('change_locale.x','1'));if(PAYPAL.rosettaRetrofit.Flash.formContextHidden){document.getElementById("rosetta").appendChild(PAYPAL.rosettaRetrofit.Flash.createRosettaFields(PAYPAL.rosettaRetrofit.Flash.formContextHidden.name,PAYPAL.rosettaRetrofit.Flash.formContextHidden.value));}
document.getElementById("rosetta").submit();},closeWidget:function(e){var flashReference=document.getElementById("rosettaFlashId");if(flashReference){if(e.target){if(e.target.id!="rosettaFlashId"){flashReference.clearPD();}}
else{flashReference.clearPD();}}},stringFromRosettaDropDown:function(){var formid=document.getElementById("rosetta");if(formid){var strToFlash="lang_Array=";if(formid["locale.x"]){this.formreference=formid["locale.x"];}
else{this.formreference=formid["user_locale.x"];}
var frmOptions=this.formreference.options;for(j=0;j<frmOptions.length;j++){strToFlash+=frmOptions[j].text+","+frmOptions[j].value;if(j<frmOptions.length-1){strToFlash+="|";}}
var hostPageUrl=window.location.href;var domainExp=/^https?:\/\/(.*?)\.paypal\.(com|co\.uk|de|au|fr|ch|com\.hk|com\.mx)(.*?)/i;var checkDomain=domainExp.test(hostPageUrl);strToFlash+="&selIndex="+this.formreference.selectedIndex;if(checkDomain){strToFlash+="&allowAccess=yes";}
if(formid["CONTEXT"]){this.formContextHidden=formid["CONTEXT"];}
return strToFlash;}},createRosettaFields:function(htmlElementName,htmlElementValue){var createId=document.createElement("input");createId.type="hidden";createId.name=htmlElementName;createId.value=htmlElementValue;return createId;}}
YAHOO.util.Event.addListener(document,'click',PAYPAL.rosettaRetrofit.Flash.closeWidget);YAHOO.util.Event.onContentReady("rosettaFlashId",function(){document.getElementById("rosettaFlashId").style.outline=0;});