
vjo.ctype("vjo.dsf.window.utils.VjWindowUtils").props({getBrowserWindowHeight:function(){var s=self;var d=document;var de=d.documentElement;if(s.innerHeight){return s.innerHeight;}else{if(de&&de.clientHeight){return de.clientHeight;}}
return d.body.clientHeight;},getBrowserWindowWidth:function(){var s=self;var d=document;var de=d.documentElement;if(s.innerWidth){return s.innerWidth;}else{if(de&&de.clientWidth){return de.clientWidth;}}
return d.body.clientWidth;},getScrollXY:function(){var _7=0,scrOfY=0;if(typeof(window.pageYOffset)=="number"){scrOfY=window.pageYOffset;_7=window.pageXOffset;}else{if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){scrOfY=document.body.scrollTop;_7=document.body.scrollLeft;}else{if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){scrOfY=document.documentElement.scrollTop;_7=document.documentElement.scrollLeft;}}}
return[_7,scrOfY];},toPixels:function(_8){return _8+"px";},scrollTop:function(){if(window.pageYOffset!=null){return window.pageYOffset;}
if(document.documentElement){return Math.max(document.documentElement.scrollTop,document.body.scrollTop);}else{return document.body.scrollTop;}},scrollLeft:function(){if(window.pageXOffset!=null){return window.pageXOffset;}
if(document.documentElement){return Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);}else{return document.body.scrollLeft;}},scrollWidth:function(){if(document.documentElement){return document.documentElement.scrollWidth;}else{return Math.max(document.body.scrollWidth,document.body.offsetWidth);}},scrollHeight:function(){if(document.documentElement){return document.documentElement.scrollHeight;}else{return Math.max(document.body.scrollHeight,document.body.offsetHeight);}},clientTop:function(){if(document.documentElement){return document.documentElement.clientTop;}else{return document.body.clientTop;}},clientLeft:function(){if(document.documentElement){return document.documentElement.clientLeft;}else{return document.body.clientLeft;}},clientWidth:function(){var _9=document.documentElement;if(_9&&window.innerWidth){return Math.min(_9.clientWidth,window.innerWidth);}else{if(_9&&_9.clientWidth){return _9.clientWidth;}else{if(window.innerWidth){return window.innerWidth;}else{if(document.body.clientWidth){return document.body.clientWidth;}else{return document.body.offsetWidth;}}}}},clientHeight:function(){var _a=document.documentElement;if(_a&&window.innerHeight){return Math.min(_a.clientHeight,window.innerHeight);}else{if(_a&&_a.clientHeight){return _a.clientHeight;}else{if(window.innerHeight){return window.innerHeight;}else{if(document.body.clientHeight){return document.body.clientHeight;}else{return document.body.offsetHeight;}}}}},browserTop:function(){return(window.innerHeight)?window.screenY+(window.outerHeight-window.innerHeight):window.screenTop;},browserLeft:function(){return(window.innerWidth)?window.screenX+(window.outerWidth-window.innerWidth):window.screenLeft;},eventTop:function(_b){if(_b.pageY!=null){return _b.pageY;}
if(document.documentElement){return _b.clientY+Math.max(document.documentElement.scrollTop,document.body.scrollTop);}else{return _b.clientY+document.body.scrollTop;}},eventLeft:function(_c){if(_c.pageX!=null){return _c.pageX;}
if(document.documentElement){return _c.clientX+Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);}else{return _c.clientX+document.body.scrollLeft;}},offsetTop:function(_d){var _e=(document.documentElement&&document.documentElement.clientTop)?document.documentElement.clientTop:0;for(var _f=0;(_d!=null);_d=_d.offsetParent){_f+=_d.offsetTop;}
return _f+_e;},offsetLeft:function(_10){var _11=(document.documentElement&&document.documentElement.clientLeft)?document.documentElement.clientLeft:0;for(var _12=0;(_10!=null);_10=_10.offsetParent){_12+=_10.offsetLeft;}
return _12+_11;},openWindow:function(url,_14,_15){var _16=new Array();var _17=vjo.dsf.window.utils.VjWindowUtils;_15.top=_17.browserTop()+Math.round((_17.clientHeight()-_15.height)/2)+25;_15.left=_17.browserLeft()+Math.round((_17.clientWidth()-_15.width)/2);for(var key in _15){_16.push(key.concat("=",_15[key]));}
return window.open(url,_14,_16.join(","),true);}}).endType();
vjo.ctype("vjo.darwin.sharedpres.flash.FlashHelper").needs("vjo.dsf.Enc").props({AddFlash:function(_1){var so=new SWFObject(_1.url,"flash_"+_1.containerName,_1.width,_1.height,_1.minVersion,_1.bgcolor,false);so.addParam("allowscriptaccess",_1.allowscriptaccess);so.addParam("allownetworking",_1.allownetworking);so.addParam("wmode",_1.wmode);so.addVariable("ebayConfig",vjo.dsf.Enc.encodeURIComponent(_1.ebayConfig||""));so.addVariable("ebayData",vjo.dsf.Enc.encodeURIComponent(_1.ebayData||""));so.addVariable("ebayContent",vjo.dsf.Enc.encodeURIComponent(_1.ebayContent||""));var _3=document.title;if(!so.write(_1.containerName)){var o=document.getElementById(_1.containerName);if(o){o.innerHTML=_1.noFlashMsg||"";}}
document.title=_3;}}).endType();
vjo.ctype('vjo.darwin.sharedpres.flash.SwfobjectDef').endType();if(typeof deconcept=="undefined"){var deconcept=new Object();}
if(typeof deconcept.util=="undefined"){deconcept.util=new Object();}
if(typeof deconcept.SWFObjectUtil=="undefined"){deconcept.SWFObjectUtil=new Object();}
deconcept.SWFObject=function(_1,id,w,h,_5,c,_7,_8,_9,_a,_b){if(!document.createElement||!document.getElementById){return;}
this.DETECT_KEY=_b?_b:"detectflash";this.skipDetect=deconcept.util.getRequestParameter(this.DETECT_KEY);this.params=new Object();this.variables=new Object();this.attributes=new Array();if(_1){this.setAttribute("swf",_1);}
if(id){this.setAttribute("id",id);}
if(w){this.setAttribute("width",w);}
if(h){this.setAttribute("height",h);}
if(_5){this.setAttribute("version",new deconcept.PlayerVersion(_5.toString().split(".")));}
this.installedVer=deconcept.SWFObjectUtil.getPlayerVersion(this.getAttribute("version"),_7);if(c){this.addParam("bgcolor",c);}
var q=_8?_8:"high";this.addParam("quality",q);this.setAttribute("useExpressInstall",_7);this.setAttribute("doExpressInstall",false);var _d=(_9)?_9:window.location;this.setAttribute("xiRedirectUrl",_d);this.setAttribute("redirectUrl","");if(_a){this.setAttribute("redirectUrl",_a);}};deconcept.SWFObject.prototype={setAttribute:function(_e,_f){this.attributes[_e]=_f;},getAttribute:function(_10){return this.attributes[_10];},addParam:function(_11,_12){this.params[_11]=_12;},getParams:function(){return this.params;},addVariable:function(_13,_14){this.variables[_13]=_14;},getVariable:function(_15){return this.variables[_15];},getVariables:function(){return this.variables;},getVariablePairs:function(){var _16=new Array();var key;var _18=this.getVariables();for(key in _18){_16.push(key+"="+_18[key]);}
return _16;},getSWFHTML:function(){var _19="";var wmodestr=this.getParams()["wmode"];if(wmodestr==null){wmodestr="transparent";}
if(navigator.plugins&&navigator.mimeTypes&&navigator.mimeTypes.length){if(this.getAttribute("doExpressInstall")){this.addVariable("MMplayerType","PlugIn");}
_19="<param name=\"wmode\" value=\""+wmodestr+"\"/> <embed wmode=\""+wmodestr+"\" type=\"application/x-shockwave-flash\" src=\""+this.getAttribute("swf")+"\" width=\""+this.getAttribute("width")+"\" height=\""+this.getAttribute("height")+"\"";_19+=" id=\""+this.getAttribute("id")+"\" name=\""+this.getAttribute("id")+"\" ";var _1a=this.getParams();for(var key in _1a){_19+=[key]+"=\""+_1a[key]+"\" ";}
var _1c=this.getVariablePairs().join("&");if(_1c.length>0){_19+="flashvars=\""+_1c+"\"";}
_19+="/>";}else{if(this.getAttribute("doExpressInstall")){this.addVariable("MMplayerType","ActiveX");}
_19="<object id=\""+this.getAttribute("id")+"\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+this.getAttribute("width")+"\" height=\""+this.getAttribute("height")+"\">";_19+="<param name=\"movie\" value=\""+this.getAttribute("swf")+"\" />";var _1d=this.getParams();for(var key in _1d){_19+="<param name=\""+key+"\" value=\""+_1d[key]+"\" />";}
var _1f=this.getVariablePairs().join("&");if(_1f.length>0){_19+="<param name=\"flashvars\" value=\""+_1f+"\" />";}
_19+="</object>";}
return _19;},write:function(_20){if(this.getAttribute("useExpressInstall")){var _21=new deconcept.PlayerVersion([6,0,65]);if(this.installedVer.versionIsValid(_21)&&!this.installedVer.versionIsValid(this.getAttribute("version"))){this.setAttribute("doExpressInstall",true);this.addVariable("MMredirectURL",encodeURIComponent(this.getAttribute("xiRedirectUrl")));document.title=document.title.slice(0,47)+" - Flash Player Installation";this.addVariable("MMdoctitle",document.title);}}
if(this.skipDetect||this.getAttribute("doExpressInstall")||this.installedVer.versionIsValid(this.getAttribute("version"))){var n=(typeof _20=="string")?document.getElementById(_20):_20;n.innerHTML=this.getSWFHTML();return true;}else{if(this.getAttribute("redirectUrl")!=""){document.location.replace(this.getAttribute("redirectUrl"));}}
return false;}};deconcept.SWFObjectUtil.getPlayerVersion=function(_23,_24){var _25=new deconcept.PlayerVersion([0,0,0]);if(navigator.plugins&&navigator.mimeTypes.length){var x=navigator.plugins["Shockwave Flash"];if(x&&x.description){_25=new deconcept.PlayerVersion(x.description.replace(/([a-z]|[A-Z]|\s)+/,"").replace(/(\s+r|\s+b[0-9]+)/,".").split("."));}}else{try{var axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");for(var i=3;axo!=null;i++){axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+i);_25=new deconcept.PlayerVersion([i,0,0]);}}
catch(e){}
if(_23&&_25.major>_23.major){return _25;}
if(!_23||((_23.minor!=0||_23.rev!=0)&&_25.major==_23.major)||_25.major!=6||_24){try{_25=new deconcept.PlayerVersion(axo.GetVariable("$version").split(" ")[1].split(","));}
catch(e){}}}
return _25;};deconcept.PlayerVersion=function(_29){this.major=parseInt(_29[0])!=null?parseInt(_29[0]):0;this.minor=parseInt(_29[1])||0;this.rev=parseInt(_29[2])||0;};deconcept.PlayerVersion.prototype.versionIsValid=function(fv){if(this.major<fv.major){return false;}
if(this.major>fv.major){return true;}
if(this.minor<fv.minor){return false;}
if(this.minor>fv.minor){return true;}
if(this.rev<fv.rev){return false;}return true;};deconcept.util={getRequestParameter:function(_2b){var q=document.location.search||document.location.hash;if(q){var _2d=q.indexOf(_2b+"=");var _2e=(q.indexOf("&",_2d)>-1)?q.indexOf("&",_2d):q.length;if(q.length>1&&_2d>-1){return q.substring(q.indexOf("=",_2d)+1,_2e);}}return"";}};if(Array.prototype.push==null){Array.prototype.push=function(_2f){this[this.length]=_2f;return this.length;};}
var getQueryParamValue=deconcept.util.getRequestParameter;var FlashObject=deconcept.SWFObject;var SWFObject=deconcept.SWFObject;
// en_US/e661/SignInApp_SignIn_e66110874621_3_en_US
// b=10874621